MobileShopApp/MobileShop/Models/HomeViewModel.cs
using MobileShop.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MobileShop.Models
{
    public class HomeViewModel
    {
        public IEnumerable<Phone> AllPhones { get; set; }

    }
}

MobileShopApp/MobileShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MobileShop.Entities;
using MobileShop.Models;
using MobileShop.Service.Interfaces;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MobileShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IPhoneService _phoneService;

        public HomeController(ILogger<HomeController> logger, IPhoneService phoneService)
        {
            _logger = logger;
            _phoneService = phoneService;
        }

        public IActionResult Index()
        {
            var phones = _phoneService.GetPhones();
            var homeViewModel = new HomeViewModel()
            {
                AllPhones = phones
            };
            return View(homeViewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MobileShopApp/MobileShop/Controllers/PhoneController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MobileShop.Entities;
using MobileShop.Models;
using MobileShop.Service.Interfaces;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace MobileShop.Controllers
{
    public class PhoneController : Controller
    {
        private readonly IPhoneService _phoneService;
        private readonly IManufacturerService _manufacturerService;
        private readonly ILogger<PhoneController> _logger;

        public PhoneController(IPhoneService phoneService, IManufacturerService manufacturerService, ILogger<PhoneController> logger)
        {
            _phoneService = phoneService;
            _manufacturerService = manufacturerService;
            _logger = logger;
        }

        // GET: PhoneController
        public ActionResult Index()
        {
            var phones = _phoneService.GetPhones();
            return View(phones);
        }

        // GET: PhoneController/Details/5
        public ActionResult Details(int id)
        {
            var phone = _phoneService.GetPhoneByID(id);
            return View(phone);
        }

        // GET: PhoneController/Create
        public ActionResult Create()
        {
            var manufacturers = _manufacturerService.GetManufacturers();
            var dropdown = _phoneService.ManufacturerDropdown(manufacturers);
            ViewBag.ManufacturerList = dropdown;
            return View();
        }

        // POST: PhoneController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PhoneViewModel model)
        {
            var phone = new Phone();
            phone.Battery = model.Battery;
            phone.Display = model.Display;
            phone.ManufacturerID = model.ManufacturerID;
            phone.Memory = model.Memory;
            phone.Model = model.Model;
            phone.Price = model.Price;
            phone.ManufacturerName = model.ManufacturerName;

            _phoneService.Add(phone);
            _logger.LogInformation("New phone was created.");
            return RedirectToAction(nameof(Index));
        }

        // GET: PhoneController/Edit/5
        public ActionResult Edit(int id)
        {
            var phone = _phoneService.GetPhoneByID(id);
            var manufacturers = _manufacturerService.GetManufacturers();
            var dropdown = _phoneService.ManufacturerDropdown(manufacturers);
            ViewBag.ManufacturerList = dropdown;
            return View(phone);
        }

        // POST: PhoneController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Phone phone)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _phoneService.Edit(phone);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception exception)
            {

                throw;
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: PhoneController/Delete/5
        public ActionResult Delete(int id)
        {
            var phone = _phoneService.GetPhoneByID(id);
            return View(phone);
        }

        // POST: PhoneController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Phone phone)
        {
            try
            {
                _phoneService.Delete(phone);
                _logger.LogInformation("One phone was deleted.");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public JsonResult CreateAJAX(Phone phone)
        {
             _phoneService.Add(phone);
            return Json(new { data = phone } );
        }

        [HttpPost]
        public IActionResult UploadImage()
        {
            try
            {
                var file = Request.Form.Files[0];
                var folderName = Path.Combine("wwwroot", "img");
                var pathToSave = Path.Combine(Directory.GetCurrentDirectory(), folderName);

                if (file.Length > 0)
                {
                    var fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                    var fullPath = Path.Combine(pathToSave, fileName);
                    var dbPath = fileName;

                    using (var stream = new FileStream(fullPath, FileMode.Create))
                    {
                        file.CopyTo(stream);
                    }

                    return Ok(new { dbPath });
                }
                else
                {
                    return BadRequest();
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Internal Server Error: " + ex);
            }
        }

    }
}

MobileShopApp/MobileShop/Views/Home/Index.cshtml
@model MobileShop.Models.HomeViewModel

<!-- Search section -->

<form asp-action="Search">
    <div class="row searchBot">
        <div class="col-sm-12 col-md-6 offset-3">
            <button class="btn searchIcon">
                <i class="fas fa-search"></i>
            </button>
            <input type="text" class="form-control inputBar" />
            <button class="btn btn-success searchBtn">Search</button>
        </div>
    </div>
</form>

<!-- Phones section -->

<div class="row">
    @foreach (var phone in Model.AllPhones)
    {
        <div class="col-sm-6 col-md-3 my-4">
            <div class="flip-card" style="width: 200px; height: 250px;">
                <div class="flip-card-inner">
                    <div class="flip-card-front">
                        <img src="~/img/@phone.PhotoURL" alt="Mobile phone picture" style="width:200px;height:250px;">
                    </div>
                    <div class="flip-card-back">
                        <h4>@phone.Model</h4>
                        <p>Display: @phone.Display</p>
                        <p>Battery: @phone.Battery</p>
                        <p>Memory: @phone.Memory</p>
                        <p><em>@phone.Price</em></p>
                        <a class="btn btn-info btn-sm specBtn" asp-controller="Phone" asp-action="Details" asp-route-id="@phone.PhoneID"><i class="fas fa-info-circle"></i> Specifications</a>
                        <button class="btn btn-dark btn-sm" data-toggle="modal" data-target="#phoneModal"><i class="fas fa-cash-register"></i> Order</button>
                    </div>
                </div>
            </div>
        </div>
    }
</div>



<div class="modal" id="phoneModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center">Order</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label class="control-label">Name:</label>
                    <input type="text" class="form-control" />
                </div>
                <div class="form-group">
                    <label class="control-label">Address:</label>
                    <input type="text" class="form-control" />
                </div>
                <div class="form-group">
                    <label class="control-label">City:</label>
                    <input type="text" class="form-control" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">Order phone</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>